version: "3"
services:

  client:
    container_name: client
    image: hicsail/restore-client:latest
    build:
      context: ./packages/client
    restart: unless-stopped
    ports:
      - "5173:5173"

  strapi:
    container_name: strapi
    image: hicsail/restore-strapi:latest
    build:
      context: ./packages/strapi
      #dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      # DATABASE_SSL does not behave the way you expect it to. Ask this committer.
      # In any case: set to false since we are using the docker network.
      DATABASE_SSL: "false"
      # Set these in Portainer, or in a .env for local development; see .env.example.
      # NB: If they are set in Portainer they don't actually have to be listed here, but let's list them bc documentation.
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/

    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
